#!/bin/bash
echo This is a small script to push a git repository.
echo Enter a commit message: 
commitmsg="$(gits.py)"
git config --get user.name
git config --get user.email
git add *
git checkout
git commit -m "$commitmsg"
git push -u origin master

